FROM ubuntu:24.04

ENV TERM xterm
ENV LANG C.UTF-8
ENV LC_ALL C.UTF-8
ENV TZ=Europe/Warsaw
# saves time with confirmation of keyboard for xvfb installation
ENV DEBIAN_FRONTEND=noninteractive

# Updating base software repository and adding ondrej repo

RUN apt update && \
    apt install -y software-properties-common && \
    add-apt-repository ppa:ondrej/php -y && \
    apt update

# Installing PHP - basics
# FYI if that fails, most probably there is a slightly newer version available and this one is outdated
# use rebuild instead of build 
# ./console r ...
# instead of
# ./console b ...

# Installing git zip 7z (for some composer repos)
RUN apt install -y git zip p7zip-full

RUN apt install -y php5.6 php5.6-common php5.6-cli php5.6-fpm

# Installing PHP - modules
RUN apt install -y php5.6-curl php5.6-json php5.6-mcrypt php5.6-mysql php5.6-opcache php5.6-readline php5.6-xml php5.6-zip

# Installing mysql-client (for some automation)
RUN apt install -y mysql-client

# Installing composer
RUN apt install -y wget
RUN cd /root && \
    wget https://getcomposer.org/download/latest-2.2.x/composer.phar && \
    chmod a+x composer.phar && \
    mv composer.phar /usr/bin/composer

# We need Ruby and compass for assetic dump in Symfony 2

RUN apt install -y ruby ruby-dev
RUN gem install compass

# We need to fix compass installation it has errors (some methods are not supported in new Ruby)
RUN cd /var/lib/gems/3.2.0/gems/compass-1.0.3/lib/compass
RUN for i in `find -name '*rb'`; do sed -i 's/File.exists/File.exist/g' $i; done

# Clean UP
RUN apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Fixing FPM configuration and process file requirement
RUN sed -i "s/^listen = .*/listen = 172.16.70.13:9000/g" /etc/php/5.6/fpm/pool.d/www.conf && \
    if [! -d /run/php]; then mkdir /run/php; chmod 755 /run/php; fi

RUN sed -i "s/^post_max_size = .*/post_max_size = 10M/g" /etc/php/5.6/fpm/php.ini && \
    sed -i "s/^upload_max_filesize = .*/upload_max_filesize = 10M/g" /etc/php/5.6/fpm/php.ini

RUN sed -i 's/^error_reporting = .*/error_reporting = E_ALL/' /etc/php/5.6/fpm/php.ini && \
    sed -i 's/^display_errors = .*/display_errors = On/'  /etc/php/5.6/fpm/php.ini && \
    sed -i 's/^log_errors = .*/log_errors = On/'  /etc/php/5.6/fpm/php.ini && \
    sed -i 's/;error_log = syslog/error_log = \/var\/log\/php5.6-fpm.log/' /etc/php/5.6/fpm/php.ini

WORKDIR /portal

ENTRYPOINT ["/usr/sbin/php-fpm5.6", "-F"]
# ENTRYPOINT ["tail", "-f", "/dev/null"] # Use this for resolution of issues
