FROM nginx:alpine

ENV TERM xterm
ENV LANG C.UTF-8
ENV LC_ALL C.UTF-8
ENV TZ=Europe/Warsaw

COPY local.docker.site.nginx.conf /etc/nginx/conf.d/default.conf

WORKDIR /portal

#RUN mkdir /run/nginx
#ENTRYPOINT ["tail", "-f", "/dev/null"]
ENTRYPOINT ["/usr/sbin/nginx-debug", "-g", "daemon off;"]
